name: lte-run-regression-tests

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runtime: [ linux, mac, windows ]
        include:
        - runtime: linux
          os: ubuntu-latest
          setupCmd: ./tests/resources/ci/scripts/setup.sh
          execCmd: ./tests/resources/ci/scripts/exec.sh

        - runtime: mac
          os: macOS-latest
          setupCmd: ./tests/resources/ci/scripts/setup.sh
          execCmd: ./tests/resources/ci/scripts/exec.sh

        - runtime: windows
          os: windows-latest
          setupCmd: bash ./tests/resources/ci/scripts/setup.sh
          execCmd: bash ./tests/resources/ci/scripts/exec.sh

    name: Build Plugin
    runs-on: ${{ matrix.os }}

    steps:
      # Checkout the eclipse plugin repository.
      - name: 'Setup: Checkout plugin'
        uses: actions/checkout@v2

      # Install the required software.
      - name: 'Setup: Install required software' 
        run: ${{ matrix.setupCmd }}
        
      # Build the plugin.
      - name: 'Build: Build-Package-RunTests'
        run: ${{ matrix.execCmd }}
